name: Mobile Browserstack Tests

on:
  push:
    branches:
      - browserstack
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Display environment variables
        run: |
          echo "API_BROWSERSTACK: ${{ env.API_BROWSERSTACK }}"
          echo "LOGIN: ${{ env.LOGIN }}"
          echo "KEY: ${{ env.KEY }}"
          echo "LINK_APP: ${{ env.LINK_APP }}"
          echo "APPIUM_BROWSERSTACK: ${{ env.APPIUM_BROWSERSTACK }}"
          echo "EMAIL_BOOKING: ${{ env.EMAIL_BOOKING }}"
          echo "PASSWORD_BOOKING: ${{ env.PASSWORD_BOOKING }}"
          echo "FIRST_DATE_BOOKING: ${{ env.FIRST_DATE_BOOKING }}"
          echo "LAST_DATE_BOOKING: ${{ env.LAST_DATE_BOOKING }}"

      - name: Run tests
        run: pytest
